name: 'install'
runs:
  using: composite
  steps:
    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v1.6

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      shell: bash
      run: pnpm i