name: 'install'
runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      shell: bash
      run: pnpm i