name: Check Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-types:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run check-types
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run build
  lint:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run lint
  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run test

  tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - check-types
      - build
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install
      - name: Release tag
        run: |
          pnpm bump
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          version="v$(cat package.json | jq .version -r)"
          git commit -m "tag: $version"
          git tag "$version"
          git push
          git push --tags
        
