name: Release
on:
  push:
    tags:
      - 'v**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pnpm build
      - uses: goreleaser/goreleaser-action@v6
        with:
          workdir: 'packages/SubstraitVizCli'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm build
      - run: pnpm ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/SubstraitVizFiddle/dist
